### ISSUE TITLE
Crashes when switching input method

### ISSUE THREAD

**Issue by sdvcrx** [akiyosi/goneovim#455] opened 2023-04-10 12:19 UTC
Hello, I'm writing to report a problem I've been having with Goneovim. Every time I switch input method while using Goneovim, the application crashes unexpectedly. 

Crash logs:

```
2023-04-10 20:09:48.399 goneovim[31720:12622477] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x100241723]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Tooltip).updateText(0xc0000c2af0, 0xc000181ce0, {0xc000431698?, 0xc0000021a0?})
	github.com/akiyosi/goneovim/editor/tooltip.go:149 +0xe3
github.com/akiyosi/goneovim/editor.(*IMETooltip).parsePreeditString(0xc0000c2af0, {0xc000431698, 0x1})
	github.com/akiyosi/goneovim/editor/imetooltip.go:191 +0x52c
github.com/akiyosi/goneovim/editor.(*Workspace).InputMethodEvent(0xc00013a000, 0x1?)
	github.com/akiyosi/goneovim/editor/workspace.go:2795 +0xcd
github.com/therecipe/qt/widgets.callbackQWidget_InputMethodEvent(0x600000c33480, 0x304a642d0)
	github.com/therecipe/qt/widgets/widgets-minimal.go:22101 +0x93
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x600000c33480, 0x304a642d0)
	_cgo_gotypes.go:16519 +0x49
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0x8?, {0x100512308?, 0xc0002e04c8?})
	github.com/therecipe/qt/widgets/widgets-minimal.go:21652 +0x9f
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0x1003dc860?, {0x100512308?, 0xc0002e04c8?})
	github.com/therecipe/qt/widgets/widgets-minimal.go:21652 +0x37
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x600000c33480, 0x304a642d0)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21618 +0xff
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec()
	_cgo_gotypes.go:2493 +0x48
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	github.com/therecipe/qt/widgets/widgets-minimal.go:2903
github.com/akiyosi/goneovim/editor.InitEditor({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	github.com/akiyosi/goneovim/editor/editor.go:392 +0xf98
main.main()
	github.com/akiyosi/goneovim/cmd/goneovim/main.go:72 +0x231
```

Additional details:
- I'm using Goneovim on MacOS, and input method is Chinese
- `goneovim --version` => `v0.6.4`

Please let me know if you have any suggestions or if you need any additional information.

**Comment by akiyosi** [comment] 2023-04-10 12:46
Thanks for the issue report.
I will close your report as it is a duplicate of #430 and #452.

**Closed by akiyosi** 2023-04-10 12:46 UTC
