### ISSUE TITLE
Bug: caret not redrawn where it is now.

### ISSUE THREAD

**Issue by artkpv** [akiyosi/goneovim#314] opened 2022-01-27 15:00 UTC
1. Open buffer
2. press `C-v` to open the buffer in a vertical split.
3. Press `C-w T` to open focused buffer in a separate tab.

Actual result: caret stays at the last place where it was before openning new tab. And it doesn't move, it won't be redrawn in other place but freezed. It is possible to change buffer but I don't see caret.
Expected result: caret is displayed where it should be for the new tab. 

```
❯ uname -a
Linux *** 5.15.13-**-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux
❯ spa -Q goneovim neovim
goneovim-bin 0.5.1-3
neovim 0.6.1-1
❯ goneovim --version
v0.5.1
```

![image](https://user-images.githubusercontent.com/3657998/151384388-a78758a5-89a0-4f65-84f1-c832bdfd4cd5.png)

**Comment by akiyosi** [comment] 2022-01-28 18:06
Hi,
Thanks for this issue reporting.
I think this problem is probably caused by the same bug as #309. The problem in #309 was detected in v0.5.1 and fixed in the latest version.
If you would like, please check if the problem is reproduced with the latest CI build.

https://github.com/akiyosi/goneovim/actions/runs/1762702113

**Comment by artkpv** [comment] 2022-03-14 09:42
@akiyosi Thanks. Do we know when the release with this patch will be? I'm installing on Archlinux from https://aur.archlinux.org/packages/goneovim-bin and it just downloads from the latest in the releases here.

**Comment by MuhammedZakir** [comment] 2022-03-14 18:35
> @akiyosi Thanks. Do we know when the release with this patch will be? I'm installing on Archlinux from https://aur.archlinux.org/packages/goneovim-bin and it just downloads from the latest in the releases here.

I don't remember if I posted this before... I think if this project releases nightly versions like WezTerm does, that would be nice as this would give us a static URL for latest builds.

[1] https://github.com/wez/wezterm/releases/nightly
[2] https://github.com/wez/wezterm/actions/runs/1978464148/workflow#L103-L117

**Comment by akiyosi** [comment] 2022-03-15 13:03
@artkpv @MuhammedZakir 
I have just released a nightly build.
https://github.com/akiyosi/goneovim/releases/tag/nightly

**Comment by akiyosi** [comment] 2022-05-27 12:16
Closed.

**Closed by akiyosi** 2022-05-27 12:16 UTC
