### ISSUE TITLE
Syntax highlighting disappears when winhighlight option is set

### ISSUE THREAD

**Issue by AdamTillou** [akiyosi/goneovim#179] opened 2020-11-14 22:04 UTC
When switching between windows, or occasionally just when making changes to a file, the syntax highlighting in some sections of the file completely disappear and the text all turns white. This happens until the cursor is moved over each line where the highlighting was removed, and the highlighting is restored.

**Comment by akiyosi** [comment] 2020-11-15 04:13
Hi, thanks for this issue report.
I have been checking on this issue and have not been able to find the cause for a long time. At this point, I don't know if it's a front-end issue or a bug in the nvim core part of the back-end.
I'd like to confirm with you that my understanding is that this issue is not 100% reproducible, but rather occurs at some point in time (under hidden conditions), but is it the same in your environment? Do you have any guesses about any hidden conditions?

To avoid this problem, you could consider installing nvim-treesitter.

**Comment by AdamTillou** [comment] 2020-11-15 19:00
Thanks for your quick response,
I figured out that it is the winhighlight option being set that causes the highlighting to be messed up. I have a plugin installed that will change the background color of the current window to make it obvious which is active, and when I disabled it the problems with highlighting went away. I have also changed the name of the thread to reflect what seems to be the real problem.

For the hidden conditions you were referring to, it seems that the highlighting gets cleared right when setting the winhighlight option, as well as when opening folds or entering insert mode for a brief period of time after setting it. Hopefully that is helpful in figuring out why this is happening.

Certainly it won't be a problem living without winhl until this is fixed, given that this is by far my favorite neovim gui program (and I've tried about a dozen.) Thank you for your incredible work making this!

**Comment by akiyosi** [comment] 2020-11-20 13:37
hi
Sorry for the delay in replying.
I appreciate your information.

> I figured out that it is the winhighlight option being set that causes the highlighting to be messed up. I have a plugin installed that will change the background color of the current window to make it obvious which is active, and when I disabled it the problems with highlighting went away. I have also changed the name of the thread to reflect what seems to be the real problem.

What are the plugins to control winhighlight?
I have tried to run winhighlight at hand but it does not reproduce. If you would like to provide some more information, I would appreciate it.

**Comment by AdamTillou** [comment] 2020-11-26 03:10
The code that automatically sets the window highlighting is the following:
`highlight Inactive guibg=#1C2028`
`highlight Active guibg=#20242C`
`autocmd WinLeave * setlocal winhl=Normal:Inactive`
`autocmd WinEnter * setlocal winhl=Normal:Active`
For me though at least, this happens whenever using any winhl command no matter the context.

**Comment by AdamTillou** [comment] 2020-12-18 05:07
When I had this problem, I was running it on Manjaro using the AUR package, but after trying it on Fedora it seems to work fine, so it may be an issue with the AUR package.

**Comment by akiyosi** [comment] 2020-12-24 18:43
Thanks for the confirmation and report.
I recognized that the problem was caused by an old version of the binary provided by the AUR package.
I will close this issue.

**Closed by akiyosi** 2020-12-24 18:43 UTC
