### ISSUE TITLE
Weird character being inserted

### ISSUE THREAD

**Issue by GustavoKatel** [akiyosi/goneovim#259] opened 2021-09-03 19:18 UTC
after some time running, Goneovim starts to print weird characters whenever I insert back-tick (``), `~` and possible other chars.

This weird char is being inserted before the actual pressed key.

I don't see this happening in the terminal.

I don't really know what may be causing this, hope you can help me figure it out.

```
:!locale

LANG="en_BR.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

```
# locale in iterm

LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

I tried running with `LANG=en_BR.UTF-8 /Applications/goneovim.app/Contents/MacOS/goneovim` but the issue keeps happening after some time.

https://user-images.githubusercontent.com/1891977/132055333-9441ed01-bf83-4355-a518-d55275dc853f.mov

**Comment by akiyosi** [comment] 2021-09-04 14:11
Hi :)
Thank you for reporting this issue.
It is critical as a problem and I would like to investigate it as a priority.

By the way, I use Goneovim to develop on a daily basis on my own MacOS device, but I have never encountered this problem, so I' m wondering if there are conditions under which it occurs.

I have found `nvim` and `goneovim` configs in your dotfiles repository and would like to look at them to find an environment where I can reproduce the problem.

It would be helpful if you could provide the following additional information on this matter.
* Your MacOS version.
* Whether the issue is reproduced by `/Applications/goneovim.app/Contents/MacOS/goneovim -u NONE`

**Comment by GustavoKatel** [comment] 2021-09-04 15:09
hi thanks a lot for the dedication!

I have experienced this in both MacOs big sur latest m1 and i386. 

sorry, but I should have mentioned this earlier: I'm using this version https://github.com/akiyosi/goneovim/actions/runs/1019557206

it's a bit hard to test, bc I don't know exactly when it starts. I will try the command provided later today.

TIA

**Comment by GustavoKatel** [comment] 2021-09-04 15:14
And maybe this is relevant: I've setup my os to be in English, but I use a Portuguese (Brazilian) keyboard

**Comment by akiyosi** [comment] 2021-09-05 02:59
Thanks for the info!

I will continue to look into it, but one point, if possible, I would appreciate it if you could also confirm that the issue is reproduced with the latest CI build.

**Comment by GustavoKatel** [comment] 2021-09-05 18:25
hi @akiyosi I'm currently trying the latest build, but I am experiencing something weird and I'm not sure if it's related.

basically keys like `alt+p` are not being properly handled. In the command line with `<C-v>` I entered first `alt+p` and then `alt+t` and both produced a different key sequence. I was expecting either `<M-p>` or `<A-p>`

https://user-images.githubusercontent.com/1891977/132137388-e2393954-9291-4e78-914d-9f9785a595a2.mov

**Comment by GustavoKatel** [comment] 2021-09-05 18:28
also `cmd+shift+p` is producing `<S-D-P>`, before it was producing `<D-P>` (uppercase P instead of lowercas) but I guess this was a fix?

**Comment by akiyosi** [comment] 2021-09-06 13:52
Yes, the key-input handling process has been changed according to the following changes in Neovim-qt and Neovim side.
https://github.com/equalsraf/neovim-qt/issues/817
https://github.com/equalsraf/neovim-qt/pull/820

Also, the default value of the `Macmeta` option has been changed from true to false in Goneovim.
If you want to use the <M-x> key, you can do so by enabling `Macmeta`.

``` toml
[Editor]
# ...
Macmeta = true
```

Note that the `Macmeta` config is planned to be reimplemented as the vim variable `g:macmeta` in the future.

**Comment by GustavoKatel** [comment] 2021-09-19 18:37
hi @akiyosi I haven't experienced this particular issue anymore 😄 , but I'm facing another one and I'm not sure if it's related.

Whenever I copy utf-8 characters from outside of Goneovim they break inside it.

Steps to reproduce:

1- Go to https://getemoji.com/ and copy an emoji
2- Go to neovim and inspect the buffers with `:reg`. `"+` shows `??` instead of the emoji.
![image](https://user-images.githubusercontent.com/1891977/133938693-c609c75a-0424-4601-b29e-86679cb3433b.png)

It also breaks with non-emoji characters like these https://fsymbols.com/signs/tick/

However if they are already present in the buffer and I copy (select and yank) they show normal in the registers

![image](https://user-images.githubusercontent.com/1891977/133938882-dedf0096-109d-4b97-88c6-73d3107d2cf6.png)

I'm using this version: https://github.com/akiyosi/goneovim/actions/runs/1202226984

Need any other info?

**Comment by akiyosi** [comment] 2021-09-22 16:00
Hi :D

> hi @akiyosi I haven't experienced this particular issue anymore 😄 

nice!😁

> Whenever I copy utf-8 characters from outside of Goneovim they break inside it.

Could you tell me the result of running goneovim and running `:r!locale` in your environment? 
If the resulting environment variable is set to C, that may be the cause.
If so, try `export LC_ALL=en_US.UTF-8` in `.bash_profile` etc.

Also, do you have any of the following settings in your init.vim for example?

``` vimrc
let $LANG='en_US.utf8'
```

I don't know the exact cause of this problem, but it seems to occur when the `$LANG` environment variable is set in init.vim.

**Comment by GustavoKatel** [comment] 2021-09-22 16:33
locale was set in Goneovim, but not in my .zshrc. So there was a mismatch. Putting this `export LC_ALL=en_US.UTF-8` to my .zshrc fixed. Thanks again @akiyosi

**Comment by akiyosi** [comment] 2021-09-22 23:55
@GustavoKatel 
I'm glad to hear that the problem has been solved.
I will close this issue.

**Closed by akiyosi** 2021-09-22 23:55 UTC
