### ISSUE TITLE
Floating windows can end up outside the screen

### ISSUE THREAD

**Issue by melkster** [akiyosi/goneovim#316] opened 2022-02-04 08:08 UTC
Floating windows on terminal Neovim seem to adapt to always fit on screen, but this doesn't seem to happen on Goneovim, as seen in the right window of both of my two screenshots below.

Floating window in **Goneovim**:
![Selection_007](https://user-images.githubusercontent.com/15816726/152493600-3ef6c487-d04c-4551-974f-a9832ab7f5fe.png)

Floating window in **terminal Neovim**:
![Selection_008](https://user-images.githubusercontent.com/15816726/152493606-0bd0b82b-1c2b-4b52-9e0e-fb08d95e400c.png)

**Comment by akiyosi** [comment] 2022-02-04 16:09
hi
Thanks for the report.

This issue may be a problem on the part of the plugin that is generating the float window. 
Which plugin are you using to generate the float window in this screenshot?

**Comment by melkster** [comment] 2022-02-04 23:04
In the screenshot I'm just calling `vim.lsp.buf.hover()`. I can try to get back to you with a minimal config to reproduce it if you can't 🙂

**Comment by akiyosi** [comment] 2022-02-05 02:00
@melkster 
Thank you. It is very helpful to provide the minimal config.

On the other hand, there may be a simple workaround for this problem.
That is, if the float window placement process " overflows" the parent window, it should be repositioned within the parent window so that there is no overflow.
There may be such a process in the TUI implementation. I have created a binary that contains this process and would like to share it with you later.

**Comment by akiyosi** [comment] 2022-02-06 21:59
I've added a process to reposition the float window within the screen if it is outside the app screen.
Could you please try this in your environment?

https://github.com/akiyosi/goneovim/actions/runs/1802571992

**Comment by melkster** [comment] 2022-02-07 08:24
@akiyosi I'll check it out!

If it's still of any help, here's a command to reproduce the original issue. It opens a 100 character wide floating window 150 characters into the screen with the current buffer inside it (run it with the path to any file that contains some text to see that the text doesn't fit on screen).

```
goneovim -u NORC -c "call nvim_open_win(0, v:true, {'width': 100, 'height': 10, 'relative': 'editor', 'row': 10, 'col': 150})" *path/to/any/file*
```

**Comment by akiyosi** [comment] 2022-02-07 14:36
@melkster 
Thanks for the minimal config!
I believe that the above fix fixes this problem.

**Comment by melkster** [comment] 2022-02-08 08:11
@akiyosi Looks good to me! Thanks for fixing it so quickly :)

**Comment by melkster** [comment] 2022-02-15 08:10
Hi again @akiyosi! I noticed that the cursor position isn't properly rendered in the case where the window is repositioned to fit inside the window. My guess is that the cursor doesn't get repositioned like the window, and so it is rendered where it would have ended up if the floating window _wasn't_ repositioned. This means that for instance when I type inside a floating window the cursor isn't where I'm typing.

To reproduce use the command in [my previous comment](https://github.com/akiyosi/goneovim/issues/316#issuecomment-1031192701), then press `I` and try typing inside the floating window.

**Comment by melkster** [comment] 2022-02-19 22:00
Hmm not really. When I use [the command to reproduce it with no config](https://github.com/akiyosi/goneovim/issues/316#issuecomment-1031192701) the window gets repositioned correctly but the cursor position still isn't.

In [my full config](https://github.com/melkster/nvim/) it looks like the cursor might be rendered in the correct position, however now the floating window is back to not being repositioned at all like it was initially. Not sure what's up with that 🤔

**Comment by akiyosi** [comment] 2022-02-20 08:20
@melkster 
Hmmm, yes. In my environment, it seems that only linux doesn't work well. macos and Windows work as expected. I will investigate further.

**Comment by akiyosi** [comment] 2022-02-20 13:28
@melkster 
Did you use `Goneovim-latest-linux_archlinux` in the CI artifacts above?
I've checked with my archlinux and popos, and it seems that only `Goneovim-latest-linux_archlinux` doesn't work properly, while the float window repositioning process seems to work fine with `Goneovim-latest-linux`. 
I have no idea why there is such a difference between the build artifacts, though.

**Comment by melkster** [comment] 2022-02-21 12:53
Hmm that's odd. I used `Goneovim-latest-linux`.

**Comment by akiyosi** [comment] 2022-02-21 14:01
Oh... Okay, I'll continue to investigate.

**Comment by akiyosi** [comment] 2022-02-21 14:05
@melkster 
What OS are you using?

**Comment by melkster** [comment] 2022-02-21 17:11
I'm on Manjaro Linux x86_64

**Comment by akiyosi** [comment] 2022-02-23 03:43
@melkster 

I tried to reproduce the problem by setting up Manjaro Linux in a VM, but was unable to do so.
Also, I mentioned in my comment issuecomment-1046238150 that I was able to reproduce the problem only with Goneovim-latest-linux_archlinux, but when I checked again later, it seems that there was some mistake and the problem was not reproduced.

I'm wondering if I may have mistakenly used a different Goneovim binary in your environment as well.
It would be very helpful if you could reconfirm the behavior of the CI artifacts to fix this issue in your environment as well.

My feeling is that the problem is fixed in your reproduced command. On the other hand, I think it is possible that some edge cases may cause problems when complex configurations (e.g. your Neovim full configuration) are applied.

To be clear, here's what I expect


|  | fixed commit: 7a8a044 | fixed commit: 9bfdd06 |
| :--- | :---: | ---: |
| Issue where floating window may be outside the screen. | minimal config: `fixed` <br> your full config: `fixed` | minimal config: `fixed` <br> your full config: `fixed` |
| Issue where cursor position is not drawn correctly <br> when float window is repositioned to fit within the screen. | minimal config: `problem` <br> your full config: `problem` | minimal config: `fixed` <br> your full config: `may hav problem??` |

**Comment by melkster** [comment] 2022-02-24 08:28
I tried both artifacts and now the issue was resolved in `9bfdd06`, so perhaps I did use the old artifact in my [previous comment](https://github.com/akiyosi/goneovim/issues/316#issuecomment-1046111419) like you suggested.

So for `Goneovim-latest-linux` I got the following table:

|                                                       | 7a8a044                                          | 9bfdd06                                      |
| ----------------------------------------------------- | ------------------------------------------------ | -------------------------------------------- |
| Issue where floating window may be outside the screen | no config: `fixed` <br> full config: `fixed`     | no config: `fixed` <br> full config: `fixed` |
| Issue where cursor position is not drawn correctly    | no config: `problem` <br> full config: `problem` | no config: `fixed` <br> full config: `fixed` |

I also tried `Goneovim-latest-linux_archlinux` with `9bfdd06` and the issue seems to be resolved there as well.

Thank you for fixing the issue (again)! :)

**Comment by melkster** [comment] 2022-05-09 13:31
@akiyosi Is this issue back again? I tried the latest nightly (176af8d) and hover windows appear off-screen again like they did originally :thinking:

**Comment by akiyosi** [comment] 2022-05-09 15:45
@melkster 
Hmm, the most recent change does not seem to re-induce the problem noted in this issue, but there may still be edge cases.
For example, if you change the application window size with the problem reproduced, does it reposition to the corrected position?

**Comment by melkster** [comment] 2022-05-13 06:45
@akiyosi I tried building the from the latest commit today and the problem is no longer there so perhaps c0d7719e2344c6cc3ff0b6a54ace3807a7526d6c solved it :)

**Comment by akiyosi** [comment] 2022-05-13 07:20
@melkster 
Thank you for confirming!
Closed.

**Comment by melkster** [comment] 2022-05-20 11:29
Hi again @akiyosi! I noticed that in some very specific cases the floating window can still end up outside the screen. I've unsuccessfully tried to create a minimal config to reproduce it, so for now I can only reproduce it with [my full config](https://github.com/melkster/nvim). I realize that's not much to go on, but do you have any guess what could be the issue? It seems to require a very specific floating window size and cursor positon.

This is what it looks like in Goneovim:

![image](https://user-images.githubusercontent.com/15816726/169518620-a3d33fd8-2009-4085-bf9f-f1c937d5a5d9.png)

And this is how it looks in Kitty:

![image](https://user-images.githubusercontent.com/15816726/169518798-3d08839f-24d3-475a-9f9b-46c203ad9528.png)

**Comment by akiyosi** [comment] 2022-05-21 01:09
@melkster 
I am looking into your configuration, but in parallel, I have fixed the process that seems to be possible from the analysis of the source code.
I would appreciate it if you could try the following CI artifact to verify if the problem occurs or not.

https://github.com/akiyosi/goneovim/actions/runs/2359558704

**Comment by melkster** [comment] 2022-05-24 12:20
@akiyosi I tried the artifact and I could not reproduce the issue with my full config 🙂

**Comment by akiyosi** [comment] 2022-05-27 03:03
Closed.

**Closed by akiyosi** 2022-05-27 03:03 UTC
