### ISSUE TITLE
gonvim crashes when switching to another tab.

### ISSUE THREAD

**Issue by jaanauati** [akiyosi/goneovim#61] opened 2019-07-04 13:21 UTC
First of all, i wanted to thank you for your work on this editor!, I find it pretty solid (much more solid and smoother than most of vim/nvim guis).

This is a bug that I noticed that when I started to use the vim-go plugin where the editor started to crash when GoInfo command is automatically executed. 
After digging a bit I realized that the same error happens when you run any external command by using `:!<command>`.
 
Steps to reproduce:
1) in normal mode execute an external command, example `:!ls /tmp`
2) DON'T HIT ENTER, just try to switch to another tab while the command output is still being displayed.

Result:
govim hangs for some seconds and then crashes.

GonVim: v0.3.5
MacOs Mojave 10.14.5

<img width="912" alt="Screen Shot 2019-07-04 at 10 14 04" src="https://user-images.githubusercontent.com/433609/60669369-8c47ef00-9e44-11e9-810a-29db93eb9233.png">

Thank you.

**Comment by akiyosi** [comment] 2019-07-04 14:45
Hi😃
Thank you for reporting the issue.

I confirmed the reproduction step but I could not reproduce it (no crash).
Could you tell me the following additional information?

1. Contents of `~/.gonvim/setting.conf`
2. nvim version: `:version`
3. Bug repeatability in `gonvim -u NONE`

**Comment by jaanauati** [comment] 2019-07-04 14:55
Sure!:
1)
```
➜  ~ cat ~/.gonvim/setting.conf
cat: /Users/jonatan/.gonvim/setting.conf: No such file or directory
➜  ~ cat ~/.gonvim/settings.conf
cat: /Users/jonatan/.gonvim/settings.conf: No such file or directory
```
2) `:version`
<img width="1188" alt="Screen Shot 2019-07-04 at 11 51 03" src="https://user-images.githubusercontent.com/433609/60675167-19de0b80-9e52-11e9-8173-4f895e59c607.png">
3) I launched gonvim using "/Applications/gonvim.app/Contents/MacOS/gonvim -u NONE", and I confirm that error is still happening.

thanks.

**Comment by akiyosi** [comment] 2019-07-04 14:58
thank you.
sorry I made a typo.

1. Contents of ~/.gonvim/setting.toml

**Comment by jaanauati** [comment] 2019-07-04 14:59
no worries:
```  cat ~/.gonvim/setting.toml
cat: /Users/jonatan/.gonvim/setting.toml: No such file or directory```

**Comment by akiyosi** [comment] 2019-07-04 15:19
Ummm, I can't reproduced it in my environment.
This problem may be affected by the OS some settings / ver. (My environment is MacOS 10.13.6)
Could you try the following:

Step 1. access `System Preferences` > `Security & Privacy` > `Privacy`
Step 2. add `gonvim` entry to `Accessibility`  

Japan is now midnight so I will go to bed, but I will see it again tomorrow.

**Comment by jaanauati** [comment] 2019-07-04 15:39
I added gonvim to the list, then closed the app and opened it again, but the error is still happening.

![image](https://user-images.githubusercontent.com/433609/60677702-9d026000-9e58-11e9-9ce8-9ac14c4ecd10.png)

Thank you.

**Comment by akiyosi** [comment] 2019-08-11 01:30
HI,
Sorry for not being able to respond.

I'd like to check again, 
What is the command to switch to another tab in the following procedure? 
Is it a `gt` or clicking GUI tab?

> 1. in normal mode execute an external command, example :!ls /tmp
> 1. DON'T HIT ENTER, just **try to switch to another tab** while the command output is still being displayed.

Clicking on the GUI tab will hang the Gonvim application. This bug will be fixed in the future, but since this is a GUI-specific issue, I think it is considered a separate issue from the vim-go crash.

**Closed** 2020-05-31 12:20 UTC
