### ISSUE TITLE
lazygit is hard to use from terminal inside of goneovim.  left mouse click can't be received by lazygit

### ISSUE THREAD

**Issue by wellcomez** [akiyosi/goneovim#265] opened 2021-09-15 07:24 UTC
lazygit is command line git tool.
If it is launched from terminal inside goneovim, ~~keyboard event and~~  **left mouse click** can't be received by lazygit.
Any events just can be processed by view of vim.

**Comment by akiyosi** [comment] 2021-09-15 13:09
Hi :)

This problem is not reproduced in my environment. I think there are probably environment-dependent factors involved. For example, does the problem reproduce on a goneovim instance started with `goneovim -u NONE` ?
Also, please provide the following information

* Your machine environment
* The contents of `~/.config/goneovim/seetings.toml` in Goneovim

**Comment by jsbeckr** [comment] 2021-09-16 08:33
Doesn't help with your problem specifically, but a cool plugin for lazygit is: https://github.com/kdheepak/lazygit.nvim

**Comment by zeertzjq** [comment] 2021-10-04 02:02
I can reproduce this Goneovim v0.4.12, but not in latest build from artifacts. Maybe this has already been solved in a commit?

**Comment by akiyosi** [comment] 2021-10-04 02:22
@zeertzjq 
Thanks for the report.
I don't think I fixed this issue, but it may be that the fix for some other issue also fixed the problem that caused this issue.

**Comment by wellcomez** [comment] 2021-10-08 05:30
[settings.txt](https://github.com/akiyosi/goneovim/files/7308755/settings.txt)
)
I doesn't remember it is default or I have changed it  somewhere.
<img width="792" alt="截屏2021-10-08 下午1 29 33" src="https://user-images.githubusercontent.com/2755665/136503240-00eb5cdc-75ea-4577-8fc7-15c4449e9b3b.png">
 



> Doesn't help with your problem specifically, but a cool plugin for lazygit is: https://github.com/kdheepak/lazygit.nvim

no use.  root cause isn't plugin

**Comment by wellcomez** [comment] 2021-10-09 01:58
> https://github.com/akiyosi/goneovim/actions/runs/1312294290



> @wellcomez Thanks for the report. It is true that mouse clicks in lazygit do not seem to work in v0.4.12, but as @zeertzjq commented, the latest build of Goneovim does not have this problem. Please check it out.
> 
> https://github.com/akiyosi/goneovim/actions/runs/1312294290

I have check latest build, mouse left-click is still unusable.

**Comment by akiyosi** [comment] 2021-10-10 02:25
Ummm, It seems to be working fine in my environment. 
The following video shows the mouse connected to my Macbook and left-clicking. Is the mouse support in lazygit what you expect to see in the following video? Also, am I correct in assuming that this is not working in your environment?

![Oct-10-2021 11-22-41](https://user-images.githubusercontent.com/8478977/136678972-9aa826cc-8660-4f2f-adad-0edbd8689802.gif)

**Comment by zeertzjq** [comment] 2021-10-10 02:28
@wellcomez What Neovim version are you using?

**Comment by zeertzjq** [comment] 2021-10-10 02:34
> I can reproduce this Goneovim v0.4.12, but not in latest build from artifacts. Maybe this has already been solved in a commit?

Wait, I can now reproduce this.

**Comment by zeertzjq** [comment] 2021-10-10 02:38
Mouse click seems work in some window positions, but not in some others.

**Comment by zeertzjq** [comment] 2021-10-10 02:44
@wellcomez are you using a floating terminal?

**Comment by zeertzjq** [comment] 2021-10-10 02:45
It seems all mouses clicks in floating window don't work in Goneovim.

**Comment by akiyosi** [comment] 2021-10-10 02:45
Uh, mouse support on float windows is currently not yet functional.

**Comment by akiyosi** [comment] 2021-10-10 09:45
@wellcomez @zeertzjq 
I have made a fix for the mouse click handling on the float window. 
Could you please try the latest CI build as following?

https://github.com/akiyosi/goneovim/actions/runs/1325324259

**Comment by zeertzjq** [comment] 2021-10-10 10:17
Mouse clicking seems to work, although dragging doesn't.

**Comment by zeertzjq** [comment] 2021-10-10 10:19
Dragging seems to stop working for non-floating windows.

**Comment by zeertzjq** [comment] 2021-10-10 13:08
Both dragging and mouse clicking now seem fine as of <https://github.com/akiyosi/goneovim/commit/961dde1e93d8e6f0e589dec0a573b9d6a7eface6>.

**Comment by akiyosi** [comment] 2021-10-10 13:09
@zeertzjq 
Oops, Thanks :D

**Comment by akiyosi** [comment] 2021-11-23 02:08
@wellcomez 
Sorry, I missed your last comment.
If you don't mind, could you please check if you still reproduce the problem with the latest build?

https://github.com/akiyosi/goneovim/actions/runs/1492795804

**Comment by wellcomez** [comment] 2021-11-28 04:25
> @wellcomez Sorry, I missed your last comment. If you don't mind, could you please check if you still reproduce the problem with the latest build?
> 
> https://github.com/akiyosi/goneovim/actions/runs/1492795804

it looks fine

**Comment by akiyosi** [comment] 2021-11-28 05:32
@wellcomez 
Thanks for the confirmation.
Now, I will close this issue once, but if the problem recurs, you may reopen it at any time.

**Comment by wellcomez** [comment] 2021-12-03 03:22
> @wellcomez Thanks for the confirmation. Now, I will close this issue once, but if the problem recurs, you may reopen it at any time.

mouse wheel  should be taken in account  and such event should be pass to lazygit

**Comment by wellcomez** [comment] 2021-12-03 03:24
> mouse wheel should be taken in account and such event should be pass to lazygit



> 
new build still has problem with mouse wheel , such event should be pass to lazygit

**Comment by akiyosi** [comment] 2021-12-04 17:20
@wellcomez 
Let me check. Is the "new build" the same version as the build I mentioned?

Also, would it be possible to share a video of the scene where the problem occurs?
I can't reproduce the problem in my environment, and it seems to me that it would be faster to see the actual problem in your environment.

**Closed** 2024-03-07 06:24 UTC
