### ISSUE TITLE
Goneovim will Randomly crash on me. Which causes me to lose work(even if I saved)

### ISSUE THREAD

**Issue by TylerAldrich814** [akiyosi/goneovim#462] opened 2023-04-22 17:04 UTC
Not sure what's causing this. I'll be working, and all of a sudden, GoNeovim will crash, and My terminal will give me an 'Invalid Memory Address or Nil Pointer dereference' Error.. 
What's even more annoying, is that What ever I've saved in the past 5 minutes or so will be gone. As if when I save in Goneovim, it doesn't actually save to the file?

Here's the output.. 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x100241723]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Tooltip).updateText(0xc000140a80, 0xc001e159e0, {0xc0002f1990?, 0xc0000021a0?})
        github.com/akiyosi/goneovim/editor/tooltip.go:149 +0xe3
github.com/akiyosi/goneovim/editor.(*IMETooltip).parsePreeditString(0xc000140a80, {0xc0002f1990, 0x2})
        github.com/akiyosi/goneovim/editor/imetooltip.go:191 +0x52c
github.com/akiyosi/goneovim/editor.(*Workspace).InputMethodEvent(0xc0001a4000, 0x1?)
        github.com/akiyosi/goneovim/editor/workspace.go:2795 +0xcd
github.com/therecipe/qt/widgets.callbackQWidget_InputMethodEvent(0x1098c6750, 0x304c88610)
        github.com/therecipe/qt/widgets/widgets-minimal.go:22101 +0x93
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x1098c6750, 0x304c88610)
        _cgo_gotypes.go:16519 +0x49
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0x8?, {0x100512308?, 0xc000d02db0?})
        github.com/therecipe/qt/widgets/widgets-minimal.go:21652 +0x9f
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0x1003dc860?, {0x100512308?, 0xc000d02db0?})
        github.com/therecipe/qt/widgets/widgets-minimal.go:21652 +0x37
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x1098c6750, 0x304c88610)
        github.com/therecipe/qt/widgets/widgets-minimal.go:21618 +0xff
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec()
        _cgo_gotypes.go:2493 +0x48
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        github.com/therecipe/qt/widgets/widgets-minimal.go:2903
github.com/akiyosi/goneovim/editor.InitEditor({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/akiyosi/goneovim/editor/editor.go:392 +0xf98
main.main()
        github.com/akiyosi/goneovim/cmd/goneovim/main.go:72 +0x231

-  2021 MacBook Pro 
- M1 Max 64Gb Ram
- Ventura 13.2.1

**Comment by akiyosi** [comment] 2023-04-23 01:37
Hi :)
I am closing this because it is a duplicate of a previous issue below.

https://github.com/akiyosi/goneovim/issues/430
https://github.com/akiyosi/goneovim/issues/452
https://github.com/akiyosi/goneovim/issues/455


I think the latest nightly build does not have this issue.

https://github.com/akiyosi/goneovim/releases/tag/nightly

**Closed by akiyosi** 2023-04-23 01:38 UTC
