### ISSUE TITLE
Status line renders strangely

### ISSUE THREAD

**Issue by darkermatter** [akiyosi/goneovim#79] opened 2019-11-23 16:37 UTC
![Screenshot from 2019-11-23 17-29-45](https://user-images.githubusercontent.com/5037324/69482098-76e55880-0e17-11ea-898f-b2d19e38da5c.png)

There are weird spaces between status line items (airline) and a white line just above the command line.

Here's what it looks like in GNvim:

![Screenshot from 2019-11-23 17-36-11](https://user-images.githubusercontent.com/5037324/69482134-d93e5900-0e17-11ea-8fc6-e779a829e40f.png)

**Comment by akiyosi** [comment] 2019-11-23 23:58
Hi,
Is it latest goneovim?
If so, I want a minimal init.vim that can reproduce the problem.

**Comment by smolck** [comment] 2019-11-24 00:22
I get the white line under the statusbar issue with a completely empty init.vim and my normal conf.

**Comment by akiyosi** [comment] 2019-11-24 00:26
@smolck 
Perhaps the problem you pointed out is the message window border? 
The border color can be controlled with the MsgSeparator highlight.

**Comment by smolck** [comment] 2019-11-24 00:28
I'm not sure; I'm talking about what @darkermatter put in the opening comment:

> . . . a white line just above the command line.

Could that be caused by the MsgSeparator highlight?

**Comment by akiyosi** [comment] 2019-11-24 00:35
>> . . . a white line just above the command line.
> 
> Could that be caused by the MsgSeparator highlight?

Yes, I think that is a message separator. So it can be controlled with `MsgSeparator` highlight

> There are weird spaces between status line items (airline) 

This is a problem with screen drawing.

**Comment by akiyosi** [comment] 2019-11-24 02:50
> There are weird spaces between status line items (airline)

I have detected the cause.
This will be fixed in v0.4.1.

**Comment by darkermatter** [comment] 2019-11-24 09:11
> Yes, I think that is a message separator. So it can be controlled with `MsgSeparator` highlight

I can confirm this. I wonder why it never showed up in terminal nvim.

**Comment by darkermatter** [comment] 2019-11-24 09:16
> > There are weird spaces between status line items (airline)
> 
> I have detected the cause.
> This will be fixed in v0.4.1.

I can also confirm that the latest commit fixes this problem.

Thanks so much Akiyoshi! :-)

**Comment by akiyosi** [comment] 2019-11-24 09:46
> I can confirm this. I wonder why it never showed up in terminal nvim.

Umm, my understanding may be inadequate. For example, the default behavior when MsgSeparator is not explicitly set. I will keep this in my mind until v0.4.2.

**Comment by darkermatter** [comment] 2019-11-24 09:50
One of those mysteries of the universe :-)

I never set it explicitly until now and it never showed in the terminal or any other gui.

**Comment by PitcherTear22** [comment] 2020-04-02 17:39
@akiyosi I have a similar issue
![goneovim](https://user-images.githubusercontent.com/36493671/78280157-29d16b80-7508-11ea-8252-8030f8668c61.png)
It renders fine in gnome-terminal:
![goneovim](https://user-images.githubusercontent.com/36493671/78280588-df042380-7508-11ea-9a5e-702eda6983e2.png)

**Comment by PitcherTear22** [comment] 2020-04-02 17:58
I even tried this minimal vimrc:
`if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'dense-analysis/ale'
Plug 'ryanoasis/vim-devicons'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

set mouse=a
set number

set runtimepath^=~/.config/nvim runtimepath+=~/.config/nvim/after
let &packpath = &runtimepath

set clipboard+=unnamedplus

let g:airline_theme='murmur'
let g:airline_powerline_fonts = 1
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#statusline#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#wordcount#filetypes = '\vasciidoc|help|mail|markdown|markdown.pandoc|org|rst|tex|text'

if exists('g:gonvim_running')
	colorscheme dracula
endif
source /home/chinmay/.config/nvim/devicons.vim
`

**Comment by PitcherTear22** [comment] 2020-04-04 17:10
goneovim version - 0.4.5-linux (from releases page)

**Comment by PitcherTear22** [comment] 2020-04-04 17:19
It renders fine when powerline fonts are disabled
(`let g:airline_powerline_fonts=1` is not set)
![goneovim-nopwerline](https://user-images.githubusercontent.com/36493671/78457238-53b99800-7698-11ea-9bf5-c5401db4d179.png)

**Comment by PitcherTear22** [comment] 2020-04-05 09:35
@akiyosi Since it renders fine without powerline, should I open a new issue?

**Comment by PitcherTear22** [comment] 2020-04-08 09:04
Solved : 
https://github.com/vim-airline/vim-airline/wiki/FAQ#the-powerline-font-symbols-are-partially-messed-up

@akiyosi Please close this

**Comment by akiyosi** [comment] 2020-04-08 12:27
@PitcherTear22 
Hmmm, I think this problem is a bug. The reason is that with the minimal vimrc you gave, goneovim lacks the highlighting of the powerline font symbol, as in your screenshot, but neovim-qt displays it correctly.
I'm debugging and don't know what's causing it.

**Comment by PitcherTear22** [comment] 2020-04-08 12:42
Hmm yes the airline wiki says this problem shouldn't exist I you use powerline fonts, so it is a bug

**Comment by PitcherTear22** [comment] 2020-04-08 12:44
But it would be better if this issue was closed and a new issue opened because it works fine without powerline fonts

**Comment by PitcherTear22** [comment] 2020-04-08 12:45
> neovim-qt displays it correctly.
Yep all other GUIs I have tried display it correctly

**Comment by akiyosi** [comment] 2020-04-08 12:51
I've confirmed that neovide has similar issues, but what about in your environment?

> But it would be better if this issue was closed and a new issue opened because it works fine without powerline fonts

I think this issue is a bug so I would like to keep the issue open or recreate it as a separate issue.

**Comment by PitcherTear22** [comment] 2020-04-08 13:11
Yes, recreate it as a separate issue

**Comment by PitcherTear22** [comment] 2020-04-08 14:16
> I've confirmed that neovide has similar issues, but what about in your environment?

Sorry, neovide is not supported by my laptop's graphics card. I'll test when I get my desktop working again.

**Comment by PitcherTear22** [comment] 2020-04-08 14:44
It also breaks the same way when you [set the column number icon by creating another section](https://github.com/ryanoasis/powerline-extra-symbols):
```
" set the CN (column number) symbol:
let g:airline_section_z = airline#section#create(["\uE0A1" . '%{line(".")}' . "\uE0A3" . '%{col(".")}'])
```

![goneovim_round_separator](https://user-images.githubusercontent.com/36493671/78797591-6b01c980-79a7-11ea-8e42-6a352e534258.png)

Although it also breaks in terminal:
![tilix_round_sep](https://user-images.githubusercontent.com/36493671/78797649-7fde5d00-79a7-11ea-9c78-6b68028edc87.png)

**Comment by akiyosi** [comment] 2020-04-14 13:49
Ugh, I have no idea what is causing this highlight disappearing problem. I've set the same GUI options as neovim-qt;

```
 rgb = true
 ext_tabline = true
 ext_popupmenu = true
 ext_linegrid = true
```

I debugged the GUI's [hl_attr_define](https://neovim.io/doc/user/ui.html#ui-event-hl_attr_define) event with the abobe option, and We can see that the neovim-qt highlights have not disappeared. 

[hl_attr_define__neovim-qt.log](https://gist.github.com/akiyosi/086ef2161d415b0041e1d22ab9f009fa)
[hl_attr_define__goneovim.log](https://gist.github.com/akiyosi/4a930c325710973f1876eb6e3727e2ae)

Number 76 and later in the log are the highlights used by the vim-airline symbol.
 I don't know why the goneovim only disappear the highlights after Number 76.

@bfredl
I'm sorry to call you on such short notice.
If you have any awareness of the cause of the problem in this matter, I would appreciate it if you could comment.

**Comment by PitcherTear22** [comment] 2020-04-28 18:59
> I've confirmed that neovide has similar issues, but what about in your environment?

Neovide doesn't have this issue but it doesn't render some powerline symbols like line number and has problems with devicons:
![image](https://user-images.githubusercontent.com/36493671/80526448-5fa32c00-89b0-11ea-9818-e5e859a01a42.png)

**Comment by akiyosi** [comment] 2020-04-29 06:43
@PitcherTear22 
Thanks for the information.
Perhaps the issue of some symbols not showing up and the issue of disappearing highlights is a separate issue.
I will continue to examine the issue of highlight disappearance, but there is no promising perspective at this time. Hmmm.

**Comment by akiyosi** [comment] 2020-04-29 17:41
I have found a workaround for this problem.
Add the following line to `init.vim`

```
set termguicolors
```

I'm not sure why the above setting gets around the problem, but I've seen this setting embedded internally in other GUIs where the highlights haven't disappeared.
I may embed this setting in the next release.

**Comment by PitcherTear22** [comment] 2020-04-29 17:56
Yep solved

**Comment by PitcherTear22** [comment] 2020-04-29 20:39
But this is an actual GUI instead of a terminal with true colour, so this shouldn't be needed right?

**Comment by akiyosi** [comment] 2020-04-30 00:58
Yes, that's exactly your point.
In fact, if you look at the vim-airline code, there is a conditional branch on `gui_running`.

However, the GUI in this context essentially refers to gvim. neovim's GUI is a completely different architecture than gvim's, and `gui_running` cannot be treated as an internal state of the neovim GUI at this time. It seems that the reason for this problem is that existing plug-ins do not recognize neovim GUI as a GUI.

In nvim-qt and gnvim, `termguicolors` are explicitly set at startup because they pseudo-recognize the plug-in side as a true color terminal, and make the GUI side notify the true color information.

Therefore, you are right to use set `termguicolors` as a workaround at this time. Of course, the next In the release, I'm going to improve it so that Goneovim automatically sets it up at boot time, even if the user doesn't set `set termguicolors`.

**Comment by PitcherTear22** [comment] 2020-04-30 03:46
> because plugins don't recognise neovim gui as a GUI.

In that case, wouldn't it be better to set `g:gui_running` internally? Or would that lead to more complications?

**Comment by akiyosi** [comment] 2020-04-30 05:34
As I understand it, `gui_running` and `g:gui_running` are two completely different properties. Currently Neovim does not provide a way for the GUI to have `gui_running`.

**Comment by PitcherTear22** [comment] 2020-04-30 05:40
oh

**Closed** 2020-05-31 12:19 UTC
