### ISSUE TITLE
[BUG] The plugin overlay character shows the wrong position

### ISSUE THREAD

**Issue by Verf** [akiyosi/goneovim#237] opened 2021-06-17 01:59 UTC
**goneovim:** https://github.com/akiyosi/goneovim/actions/runs/933042097
**OS:** Windows 10 20H2 19042.985
**Neovim:**
NVIM v0.5.0-dev+1353-g0a653f7ab
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-612
Features: -acl +iconv +tui

**vimrc:** [my vimrc](https://github.com/Verf/vimrc/tree/develop)
**settings.toml:**
```
[Editor]
FontFamily = "Sarasa Mono SC Nerd"
FontSize = 14
DisableLigatures = false
DisableImeInNormal = true
IndentGuide = false
SmoothScroll = false
ginitvim = '''
  augroup GonvimAu
    autocmd!
  augroup end
  augroup GonvimAuWorkspace
    autocmd!
  augroup end
  augroup GonvimAuFilepath
    autocmd!
  augroup end
  augroup GonvimAuMd
    autocmd!
  augroup end
  augroup GonvimAuScrollbar
    autocmd!
  augroup end
  augroup GonvimAuClipboard
    autocmd!
  augroup end
  augroup GonvimAuStatusline
    autocmd!
  augroup end
'''
[MiniMap]
Disable = true
Visible = false
[Markdown]
Disable = true
[SideBar]
Disable = true
Visible = false
```

**Demo:**
![demo](https://user-images.githubusercontent.com/22053969/122318707-187c4f80-cf52-11eb-94ca-4db5a340a9bc.png)

The overlay character generated by [lightspeed ](https://github.com/ggandor/lightspeed.nvim)does not appear in the correct position. But nvim-qt does not have this problem.

**Comment by akiyosi** [comment] 2021-06-19 13:51
Hi, thanks for the report.

This problem is fatal and I would like to fix it, but I have not succeeded in reproducing the issue in my environment :(
I am concerned about the following points

* Does the reproducibility of the event occur 100% for any given file?
* Is there anything that would prevent the event from occurring if I use a different font?

Also, is the font you are using the same as the following one? 
Do you have any manual builds or other methods of getting the fonts at hand?
https://github.com/laishulu/Sarasa-Mono-SC-Nerd

**Comment by Verf** [comment] 2021-06-23 09:16
> Hi, thanks for the report.
> 
> This problem is fatal and I would like to fix it, but I have not succeeded in reproducing the issue in my environment :(
> I am concerned about the following points
> 
> * Does the reproducibility of the event occur 100% for any given file?
> * Is there anything that would prevent the event from occurring if I use a different font?
> 
> Also, is the font you are using the same as the following one?
> Do you have any manual builds or other methods of getting the fonts at hand?
> https://github.com/laishulu/Sarasa-Mono-SC-Nerd

Sorry for the late reply, I did some tests to determine that the problem is caused by the font. [Sarasa Mono SC Nerd](https://github.com/laishulu/Sarasa-Mono-SC-Nerd) that you mentioned will cause this problem, while the fonts download from [nerdfonts.com](www.nerdfonts.com) wil not. I try to delete all my vimrc and just packadd lightspeed.nvim, the problem still occurs. Hope you can reproduce this problem, please feel free to contact me if you need any further information.

**Comment by Verf** [comment] 2021-06-24 01:28
I did the same operation on another computer and the problem no longer exists. Maybe this problem is related to my computer, I will try some new environments for testing.

**Comment by akiyosi** [comment] 2021-06-24 03:23
Thanks for the confirmation.

I have a similar view, and one of the possibilities is a bug in the qt framework, especially in newer versions of Windows10. (I have a Windows10 machine that is older than yours, and it does not reproduce this problem.

I will continue to investigate.

**Comment by akiyosi** [comment] 2021-06-26 15:54
@Verf 
I have continued to investigate this issue and have successfully reproduced the problem on my Windows 10 device.

Based on my investigation, I have determined that the issue is completely a font problem. This issue occurs when there is a difference between the width of the regular version of the font and the width of the bold one.
On my Windows 10 device, the problem is reproduced with `Courier New`, but not with `Sarasa Mono SC Nerd`. Why such a difference occurs is a mystery.

The solution to this problem is a bit difficult with the current rendering architecture. I will continue to investigate.
However, disabling the Ligature setting is a good workaround. If you are not interested in Ligature, please try the following settings in your `~/.goneovim/settings.toml`

```
[Editor]
DisableLigatures = false
```

**Comment by Verf** [comment] 2021-06-28 00:46
> @Verf
> I have continued to investigate this issue and have successfully reproduced the problem on my Windows 10 device.
> 
> Based on my investigation, I have determined that the issue is completely a font problem. This issue occurs when there is a difference between the width of the regular version of the font and the width of the bold one.
> On my Windows 10 device, the problem is reproduced with `Courier New`, but not with `Sarasa Mono SC Nerd`. Why such a difference occurs is a mystery.
> 
> The solution to this problem is a bit difficult with the current rendering architecture. I will continue to investigate.
> However, disabling the Ligature setting is a good workaround. If you are not interested in Ligature, please try the following settings in your `~/.goneovim/settings.toml`
> 
> ```
> [Editor]
> DisableLigatures = false
> ```

Thanks for you work, I can confirm that after ligatures is disabled, this problem will not occur when using `Sarasa Mono SC Nerd`. In addition, I think the way to disable ligatures is to set `DisableLigatures = true` :)

**Comment by akiyosi** [comment] 2022-05-13 16:49
This issue is closed as a Goneovim issue because it is essentially a font metrics handling issue by Qt and there is a workaround.

**Closed by akiyosi** 2022-05-13 16:49 UTC
