### ISSUE TITLE
Cannot type # on Mac OS Sonoma - E348: No String under cursor

### ISSUE THREAD

**Issue by kamransoomro84** [akiyosi/goneovim#517] opened 2024-01-22 12:11 UTC
I have `v0.6.8` on Mac OS Sonoma. My usual keys for typing # are Opt+3 but for some reason in `goneovim` this doesn't work. Every time I enter the combo, `goneovim` appears to go into normal mode and I get the error `E348: No String under cursor`.

I have confirmed that the key combo works as expected in `neovim` if I launch it from the terminal.

Any guesses what might be the issue?

**Comment by akiyosi** [comment] 2024-01-24 11:49
@kamransoomro84 
I understand that E348 is an error that is output when, for example, a keyword search is performed by `#` or `*` on an empty line.
Could you please provide a more specific situation regarding this issue? (Because it is a very natural Vim/Neovim specification in some situations.)

For example, the following information would be useful
- Example of editing file
- Cursor position before operation
- Expected behavior
- Problems with Goneovim

**Comment by kamransoomro84** [comment] 2024-01-24 12:41
Well that would kind of explain it. I am editing an empty markdown file and trying to type a level 1 heading (# Heading 1).

But I would imagine that in insert mode it should still output the # instead of escaping into normal mode and trying to search the empty line? Like I said, it works as expected in `neovim`.

Expected behaviour is that it should output the # character on the screen buffer. See gif below:

![CleanShot 2024-01-24 at 12 39 56](https://github.com/akiyosi/goneovim/assets/4132530/1b0be4bb-9ea4-4b82-b72f-ad2402b6a93c)

**Comment by akiyosi** [comment] 2024-01-24 12:59
@kamransoomro84 
Thanks for the additional information.
From the video, it seems that the mode is changed from insert mode to normal mode when `Opt+3` is pressed. 
Therefore, it seems to be behaving as pressing # with an empty line.

Could you please provide the following additional information for investigation?
- Debug.log generated by reproducing the issue with /path/to/goneovim --debug
    e.g.
    ```
    /Applications/goneovim.app/Contents/MacOS/goneovim --debug=/path/to/debug.log
    ```

**Comment by akiyosi** [comment] 2024-01-24 16:00
@kamransoomro84 
I found the cause.
The alt modifier is interpreted as valid because the option key is pressed, and the `<A-#>` key is emitted inside Goneovim.
WezTerm seems to have had a similar problem in the past. https://github.com/wez/wezterm/issues/4778


More investigation is needed to fix this problem exactly.
How is the mechanism to input # by the combination of Opt+3 key achieved, is it karabiner-elements?

**Comment by kamransoomro84** [comment] 2024-01-24 17:32
No that's the default UK keyboard layout. Not modifications.

**Comment by kamransoomro84** [comment] 2024-01-24 17:42
Thanks for the link. It appears the problem is that Opt+3 should be interpreted as a composed key but it's not as described [here](https://wezfurlong.org/wezterm/config/keyboard-concepts.html#macos-left-and-right-option-key). This problem also appears to be related to [this](https://github.com/akiyosi/goneovim/issues/408) issue.

**Comment by akiyosi** [comment] 2024-01-29 07:12
@kamransoomro84 
I have created a fix for this issue.
Would it be possible for you to test if it works as expected on your machine?

https://github.com/akiyosi/goneovim/actions/runs/7691099361

**Comment by kamransoomro84** [comment] 2024-01-29 09:10
Are there any instructions for how to test?

**Comment by akiyosi** [comment] 2024-01-29 11:31
@kamransoomro84 
I would like to confirm that the reported problem has been fixed.
If possible, I would also appreciate it if you could check the other series of keyboard inputs to see if they are also working.

Fixed binaries can be obtained from the bottom of the page linked above.

**Comment by kamransoomro84** [comment] 2024-01-29 13:02
Thanks. I can confirm that the `Opt+3` input works as expected. I tried a few others that also appear to work as expected.

**Comment by akiyosi** [comment] 2024-01-29 15:00
@kamransoomro84 
Thanks for confirming!
I will merge into master.

**Comment by akiyosi** [comment] 2024-01-31 08:00
Closed with https://github.com/akiyosi/goneovim/pull/518

**Closed by akiyosi** 2024-01-31 08:00 UTC

**Comment by josepheiba** [comment] 2024-02-02 19:10
<img width="561" alt="Screenshot 2024-02-02 at 8 08 12 PM" src="https://github.com/akiyosi/goneovim/assets/101673502/b5f1a2ad-f15f-4d32-9f2f-9a1005ffc814">

on Insert mode, on neovim, when I press option+3 to type '#', I get this error, but it only happens in one terminal emulator, so is this related to the emulator or neovim, it does not happen in vim

**Comment by kamransoomro84** [comment] 2024-02-02 20:49
I would guess that in that case it's the emulator. Neovim processes the input fine for me.
