### ISSUE TITLE
Crash from time to time

### ISSUE THREAD

**Issue by Aletz-Arce** [akiyosi/goneovim#140] opened 2020-06-30 19:01 UTC
Hi,
Thanks for great GUI frontend.
Ive been into issues where goneovim crashes randomly from time to time.
Versions:
NVIM v0.5.0-575-g225f0bcd9
Goneovim 0.4.6

Trace:
`[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7ff0f7f4c2ee]

runtime stack:
runtime.throw(0xd3c18c, 0x2a)
	runtime/panic.go:774 +0x72
fatal error: unexpected signal during runtime execution
runtime.sigpanic()
	runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xb78de0, 0xc000b211e8, 0xc001db99c0)
	runtime/cgocall.go:128 +0x5b fp=0xc000b211b8 sp=0xc000b21180 pc=0x54437b
github.com/therecipe/qt/widgets._Cfunc_QWidget_PaintEventDefault(0x2d4fba0, 0x7ffe60183dd0)
	_cgo_gotypes.go:17922 +0x45 fp=0xc000b211e8 sp=0xc000b211b8 pc=0x7882e5
github.com/therecipe/qt/widgets.(*QWidget).PaintEventDefault.func1(0xc000b21288, 0xe78300, 0xc001db99c0)
	github.com/therecipe/qt/widgets/widgets-minimal.go:23145 +0xc8 fp=0xc000b21230 sp=0xc000b211e8 pc=0x84c928
github.com/therecipe/qt/widgets.(*QWidget).PaintEventDefault(0xc000b21288, 0xe78300, 0xc001db99c0)
	github.com/therecipe/qt/widgets/widgets-minimal.go:23145 +0x57 fp=0xc000b21258 sp=0xc000b21230 pc=0x809617
github.com/therecipe/qt/widgets.callbackQWidget_PaintEvent(0x2d4fba0, 0x7ffe60183dd0)
	github.com/therecipe/qt/widgets/widgets-minimal.go:23111 +0x119 fp=0xc000b212a8 sp=0xc000b21258 pc=0x8092a9
github.com/therecipe/qt/widgets._cgoexpwrap_40e2b6255368_callbackQWidget_PaintEvent(0x2d4fba0, 0x7ffe60183dd0)
	_cgo_gotypes.go:24692 +0x35 fp=0xc000b212c8 sp=0xc000b212a8 pc=0x79d735
runtime.call32(0x0, 0x7ffe60183850, 0x7ffe601838e0, 0x10)
	runtime/asm_amd64.s:539 +0x3b fp=0xc000b212f8 sp=0xc000b212c8 pc=0x59991b
runtime.cgocallbackg1(0x0)
	runtime/cgocall.go:314 +0x1b7 fp=0xc000b213e0 sp=0xc000b212f8 pc=0x544727
runtime.cgocallbackg(0x0)
	runtime/cgocall.go:191 +0xc1 fp=0xc000b21448 sp=0xc000b213e0 pc=0x5444d1
runtime.cgocallback_gofunc(0x54439f, 0xb78340, 0xc000b214d8, 0xc000b214c8)
	runtime/asm_amd64.s:793 +0x9b fp=0xc000b21468 sp=0xc000b21448 pc=0x59aeeb
runtime.asmcgocall(0xb78340, 0xc000b214d8)
	runtime/asm_amd64.s:640 +0x42 fp=0xc000b21470 sp=0xc000b21468 pc=0x59ad82
runtime.cgocall(0xb78340, 0xc000b214d8, 0x8)
	runtime/cgocall.go:131 +0x7f fp=0xc000b214a8 sp=0xc000b21470 pc=0x54439f
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x2d4fba0, 0x7ffe60183dd0, 0x0)
	_cgo_gotypes.go:16867 +0x4a fp=0xc000b214d8 sp=0xc000b214a8 pc=0x78512a
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc000b21580, 0xe46d20, 0xc001db99b8, 0xc001db99b8)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21851 +0xb6 fp=0xc000b21520 sp=0xc000b214d8 pc=0x848546
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc000b21580, 0xe46d20, 0xc001db99b8, 0x5)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21851 +0x4d fp=0xc000b21550 sp=0xc000b21520 pc=0x8010ad
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x2d4fba0, 0x7ffe60183dd0, 0xd5ef08)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21817 +0x120 fp=0xc000b215a0 sp=0xc000b21550 pc=0x800d30
github.com/therecipe/qt/widgets._cgoexpwrap_40e2b6255368_callbackQWidget_Event(0x2d4fba0, 0x7ffe60183dd0, 0x0)
	_cgo_gotypes.go:24371 +0x35 fp=0xc000b215c8 sp=0xc000b215a0 pc=0x79c5b5
runtime.call32(0x0, 0x7ffe60183aa0, 0x7ffe60183b30, 0x18)
	runtime/asm_amd64.s:539 +0x3b fp=0xc000b215f8 sp=0xc000b215c8 pc=0x59991b
runtime.cgocallbackg1(0x0)
	runtime/cgocall.go:314 +0x1b7 fp=0xc000b216e0 sp=0xc000b215f8 pc=0x544727
runtime.cgocallbackg(0x0)
	runtime/cgocall.go:191 +0xc1 fp=0xc000b21748 sp=0xc000b216e0 pc=0x5444d1
runtime.cgocallback_gofunc(0x54439f, 0xbad110, 0xc000b217d8, 0xc000b217c8)
	runtime/asm_amd64.s:793 +0x9b fp=0xc000b21768 sp=0xc000b21748 pc=0x59aeeb
runtime.asmcgocall(0xbad110, 0xc000b217d8)
	runtime/asm_amd64.s:640 +0x42 fp=0xc000b21770 sp=0xc000b21768 pc=0x59ad82
runtime.cgocall(0xbad110, 0xc000b217d8, 0x8)
	runtime/cgocall.go:131 +0x7f fp=0xc000b217a8 sp=0xc000b21770 pc=0x54439f
github.com/akiyosi/goqtframelesswindow._Cfunc_QFramelessWindowbaaf11_EventDefault(0x24f8230, 0x879eba0, 0x0)
	_cgo_gotypes.go:347 +0x4a fp=0xc000b217d8 sp=0xc000b217a8 pc=0x8e09da
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault.func1(0xc00018dcc0, 0xe46d20, 0xc001db9920, 0xc001db9920)
	github.com/akiyosi/goqtframelesswindow/moc.go:483 +0xb8 fp=0xc000b21820 sp=0xc000b217d8 pc=0x8ef2e8
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault(0xc00018dcc0, 0xe46d20, 0xc001db9920, 0x5)
	github.com/akiyosi/goqtframelesswindow/moc.go:483 +0x4f fp=0xc000b21850 sp=0xc000b21820 pc=0x8e77af
github.com/akiyosi/goqtframelesswindow.callbackQFramelessWindowbaaf11_Event(0x24f8230, 0x879eba0, 0xd5ef08)
	github.com/akiyosi/goqtframelesswindow/moc.go:478 +0x11e fp=0xc000b21898 sp=0xc000b21850 pc=0x8e772e
github.com/akiyosi/goqtframelesswindow._cgoexpwrap_7786225e9f74_callbackQFramelessWindowbaaf11_Event(0x24f8230, 0x879eba0, 0x7ffe60185301)
	_cgo_gotypes.go:1652 +0x35 fp=0xc000b218c0 sp=0xc000b21898 pc=0x8e3205
runtime.call32(0x0, 0x7ffe60184f80, 0x7ffe60185010, 0x18)
	runtime/asm_amd64.s:539 +0x3b fp=0xc000b218f0 sp=0xc000b218c0 pc=0x59991b
runtime.cgocallbackg1(0x0)
	runtime/cgocall.go:314 +0x1b7 fp=0xc000b219d8 sp=0xc000b218f0 pc=0x544727
runtime.cgocallbackg(0x0)
	runtime/cgocall.go:191 +0xc1 fp=0xc000b21a40 sp=0xc000b219d8 pc=0x5444d1
runtime.cgocallback_gofunc(0x54439f, 0xb6f950, 0xc000b21ad0, 0x28b83d0)
	runtime/asm_amd64.s:793 +0x9b fp=0xc000b21a60 sp=0xc000b21a40 pc=0x59aeeb
runtime.asmcgocall(0xb6f950, 0xc000b21ad0)
	runtime/asm_amd64.s:640 +0x42 fp=0xc000b21a68 sp=0xc000b21a60 pc=0x59ad82
runtime.cgocall(0xb6f950, 0xc000b21ad0, 0x80b983)
	runtime/cgocall.go:131 +0x7f fp=0xc000b21aa0 sp=0xc000b21a68 pc=0x54439f
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
	_cgo_gotypes.go:2479 +0x49 fp=0xc000b21ad0 sp=0xc000b21aa0 pc=0x764249
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	github.com/therecipe/qt/widgets/widgets-minimal.go:2849
github.com/akiyosi/goneovim/editor.InitEditor()
	github.com/akiyosi/goneovim/editor/editor.go:234 +0x757 fp=0xc000b21f50 sp=0xc000b21ad0 pc=0xa8ef47
main.main()
	github.com/akiyosi/goneovim/cmd/goneovim/main.go:14 +0x20 fp=0xc000b21f60 sp=0xc000b21f50 pc=0xafd7f0
runtime.main()
	runtime/proc.go:203 +0x21e fp=0xc000b21fe0 sp=0xc000b21f60 pc=0x57062e
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc000b21fe8 sp=0xc000b21fe0 pc=0x59b631

goroutine 6 [select, 170 minutes]:
os/exec.(*Cmd).Start.func2(0xc0000b2c60)
	os/exec/exec.go:443 +0xc4
created by os/exec.(*Cmd).Start
	os/exec/exec.go:442 +0x6a6

goroutine 21 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	runtime/proc.go:310
sync.runtime_notifyListWait(0xc00024c3d0, 0x4a78)
	runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc00024c3c0)
	sync/cond.go:56 +0x9d
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).dequeueNotifications(0xc0002d6270, 0x1, 0x1, 0x0)
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:630 +0x5d
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).runNotifications(0xc0002d6270)
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:642 +0x20a
created by github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:367 +0xea

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0f0318da8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000069878, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000069860, 0xc0002dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
	os/file_unix.go:259
os.(*File).Read(0xc000215448, 0xc0002dd000, 0x1000, 0x1000, 0xc0012ebaa0, 0xc000274db0, 0xc001d63c01)
	os/file.go:116 +0x71
bufio.(*Reader).fill(0xc000069980)
	bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc000069980, 0x0, 0x0, 0x0)
	bufio/bufio.go:252 +0x39
github.com/neovim/go-client/msgpack.(*Decoder).Unpack(0xc000099220, 0x4, 0x0)
	github.com/neovim/go-client/msgpack/unpack.go:154 +0x55
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve(0xc0002d6270, 0x0, 0x0)
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:370 +0xff
github.com/neovim/go-client/nvim.(*Nvim).Serve(0xc000207a10, 0x0, 0x0)
	github.com/neovim/go-client/nvim/nvim.go:53 +0x81
github.com/neovim/go-client/nvim.(*Nvim).startServe.func1(0xc000207a10)
	github.com/neovim/go-client/nvim/nvim.go:59 +0x2b
created by github.com/neovim/go-client/nvim.(*Nvim).startServe
	github.com/neovim/go-client/nvim/nvim.go:58 +0x6c

goroutine 8 [semacquire, 170 minutes]:
sync.runtime_SemacquireMutex(0xc000207a3c, 0x0, 0x1)
	runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000207a38)
	sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
github.com/neovim/go-client/nvim.(*Nvim).Serve(0xc000207a10, 0x0, 0x0)
	github.com/neovim/go-client/nvim/nvim.go:51 +0xc3
github.com/akiyosi/goneovim/editor.(*Workspace).startNvim.func3(0xc000246000)
	github.com/akiyosi/goneovim/editor/workspace.go:330 +0x36
created by github.com/akiyosi/goneovim/editor.(*Workspace).startNvim
	github.com/akiyosi/goneovim/editor/workspace.go:329 +0x2c8

goroutine 68 [sync.Cond.Wait, 170 minutes]:
runtime.goparkunlock(...)
	runtime/proc.go:310
sync.runtime_notifyListWait(0xc0002271d0, 0x3)
	runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0002271c0)
	sync/cond.go:56 +0x9d
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).dequeueNotifications(0xc000201520, 0x1, 0x1, 0x0)
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:630 +0x5d
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).runNotifications(0xc000201520)
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:642 +0x20a
created by github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:367 +0xea

goroutine 67 [IO wait, 170 minutes]:
internal/poll.runtime_pollWait(0x7ff0f0318c08, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0004cbe78, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004cbe60, 0xc0001a1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
	os/file_unix.go:259
os.(*File).Read(0xc000450788, 0xc0001a1000, 0x1000, 0x1000, 0x922bbb, 0xc0002271c0, 0x0)
	os/file.go:116 +0x71
bufio.(*Reader).fill(0xc0004e5080)
	bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc0004e5080, 0x922874, 0xc000201520, 0xc00041c080)
	bufio/bufio.go:252 +0x39
github.com/neovim/go-client/msgpack.(*Decoder).Unpack(0xc000234460, 0x3, 0x0)
	github.com/neovim/go-client/msgpack/unpack.go:154 +0x55
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve(0xc000201520, 0x0, 0x0)
	github.com/neovim/go-client/msgpack/rpc/endpoint.go:370 +0xff
github.com/neovim/go-client/nvim.(*Nvim).Serve(0xc000320ba0, 0x0, 0x0)
	github.com/neovim/go-client/nvim/nvim.go:53 +0x81
github.com/akiyosi/goneovim/editor.(*MiniMap).startMinimapProc.func2(0xc000466000, 0xc00028caf0)
	github.com/akiyosi/goneovim/editor/minimap.go:133 +0x36
created by github.com/akiyosi/goneovim/editor.(*MiniMap).startMinimapProc
	github.com/akiyosi/goneovim/editor/minimap.go:132 +0x342

goroutine 66 [semacquire, 170 minutes]:
sync.runtime_SemacquireMutex(0xc000320bcc, 0x0, 0x1)
	runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000320bc8)
	sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
github.com/neovim/go-client/nvim.(*Nvim).Serve(0xc000320ba0, 0x0, 0x0)
	github.com/neovim/go-client/nvim/nvim.go:51 +0xc3
github.com/neovim/go-client/nvim.(*Nvim).startServe.func1(0xc000320ba0)
	github.com/neovim/go-client/nvim/nvim.go:59 +0x2b
created by github.com/neovim/go-client/nvim.(*Nvim).startServe
	github.com/neovim/go-client/nvim/nvim.go:58 +0x6c

goroutine 41 [chan receive, 170 minutes]:
github.com/akiyosi/goneovim/editor.InitEditor.func3(0xc0001f4c00)
	github.com/akiyosi/goneovim/editor/editor.go:225 +0x3b
created by github.com/akiyosi/goneovim/editor.InitEditor
	github.com/akiyosi/goneovim/editor/editor.go:224 +0x71f

goroutine 33 [select, 170 minutes]:
os/exec.(*Cmd).Start.func2(0xc0000b2000)
	os/exec/exec.go:443 +0xc4
created by os/exec.(*Cmd).Start
	os/exec/exec.go:442 +0x6a6

goroutine 1924 [syscall]:
github.com/therecipe/qt/widgets._Cfunc_QWidget_Update2(0x103f0280, 0x9000000000, 0x12000000e6)
	_cgo_gotypes.go:19237 +0x45 fp=0xc00046edb8 sp=0xc00046ed88 pc=0x78c1c5
github.com/therecipe/qt/widgets.(*QWidget).Update2.func1(0xc00028c320, 0x0, 0x90, 0xe6, 0x12)
	github.com/therecipe/qt/widgets/widgets-minimal.go:24362 +0x8c fp=0xc00046edf8 sp=0xc00046edb8 pc=0x85149c
github.com/therecipe/qt/widgets.(*QWidget).Update2(0xc00028c320, 0x0, 0x90, 0xe6, 0x12)
	github.com/therecipe/qt/widgets/widgets-minimal.go:24362 +0x6b fp=0xc00046ee30 sp=0xc00046edf8 pc=0x8104bb
github.com/akiyosi/goneovim/editor.(*Window).update(0xc001191860)
	github.com/akiyosi/goneovim/editor/screen.go:2084 +0x160 fp=0xc00046ee78 sp=0xc00046ee30 pc=0xabb640
github.com/akiyosi/goneovim/editor.(*Screen).update.func1(0xc30fc0, 0xc0017a83c0, 0xcce6c0, 0xc001191860, 0x200000001)
	github.com/akiyosi/goneovim/editor/screen.go:2116 +0x9e fp=0xc00046eeb0 sp=0xc00046ee78 pc=0xaf195e
sync.(*Map).Range(0xc0002c40c8, 0xc00046ef98)
	sync/map.go:333 +0x1c3 fp=0xc00046ef88 sp=0xc00046eeb0 pc=0x5b6703
github.com/akiyosi/goneovim/editor.(*Screen).update(0xc0002c40a0)
	github.com/akiyosi/goneovim/editor/screen.go:2094 +0x54 fp=0xc00046efb8 sp=0xc00046ef88 pc=0xabb704
github.com/akiyosi/goneovim/editor.(*Screen).mousePressEvent.func2(0xc000055750, 0xc0002c40a0)
	github.com/akiyosi/goneovim/editor/screen.go:1205 +0x46 fp=0xc00046efd0 sp=0xc00046efb8 pc=0xaf05b6
created by github.com/akiyosi/goneovim/editor.(*Screen).mousePressEvent
	github.com/akiyosi/goneovim/editor/screen.go:1202 +0x3d7
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7ff0609188f8 pc=0x7ff100752ebe]

runtime stack:
runtime.throw(0xd3c18c, 0x2a)
	runtime/panic.go:774 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:378 +0x47c`

**Comment by akiyosi** [comment] 2020-07-04 04:30
Hi,
Thanks for the report 😀

I'm looking at this issue now.
I still don't know the cause.
What is the OS you are using?

**Comment by Aletz-Arce** [comment] 2020-07-06 14:31
> Hi,
> Thanks for the report grinning
> 
> I'm looking at this issue now.
> I still don't know the cause.
> What is the OS you are using?

Hi,
My SO is Sabayon Gnome flavor. 
I'm try the last version compiled from github actions, it's the same behaviour.
I realize that crash is present when switch between apps
Thanks

**Comment by akiyosi** [comment] 2020-07-06 16:00
Thanks for additional info.

> I realize that crash is present when switch between apps

Does this mean that as long as you use it within the goneovim app, it won't crash, but if you switch to another app (e.g. google-chrome) or something else, goneovim will crash?

**Comment by Aletz-Arce** [comment] 2020-07-06 16:33
> Thanks for additional info.
> 
> > I realize that crash is present when switch between apps
> 
> Does this mean that as long as you use it within the goneovim app, it won't crash, but if you switch to another app (e.g. google-chrome) or something else, goneovim will crash?

Yes,
If goneovim window lose focus and then recover that, randomly crash appear.
Additional information:
My current setup is dual monitor over Quadro K600.

**Comment by eyalk5** [comment] 2020-07-09 21:41
How did you get such a detailed crash dump? I am using nvim-nightly and tried lldb .

**Comment by akiyosi** [comment] 2020-07-10 15:19
Hi

I have implemented some fixes that may be related to this issue.
Could you please check that the problem is fixed in the latest binaries? 

https://github.com/akiyosi/goneovim/actions/runs/164507373

**Comment by Aletz-Arce** [comment] 2020-07-10 16:34
> Hi
> 
> I have implemented some fixes that may be related to this issue.
> Could you please check that the problem is fixed in the latest binaries?
> 
> [akiyosi/goneovim/actions/runs/164507373](https://github.com/akiyosi/goneovim/actions/runs/164507373)

Sure,
I will try to use them as the main editor today :)

**Comment by Aletz-Arce** [comment] 2020-07-11 00:20
> > Hi
> > I have implemented some fixes that may be related to this issue.
> > Could you please check that the problem is fixed in the latest binaries?
> > [akiyosi/goneovim/actions/runs/164507373](https://github.com/akiyosi/goneovim/actions/runs/164507373)
> 
> Sure,
> I will try to use them as the main editor today :)
> 
> Update:
> Well it's not possible run lastest version sweat
My mistake, i didn't set execution permission to QtWebEngineProcess file.
Try again :smiley:

**Comment by akiyosi** [comment] 2020-07-11 11:22
Oh, I'm sorry, I'm sure Github Actions Workflow does grant execution rights to QWebEngineProcess, but it doesn't seem to be working well in some cases. Umm...

https://github.com/akiyosi/goneovim/blob/master/.github/workflows/go.yml#L74-L78

**Comment by Aletz-Arce** [comment] 2020-07-14 01:28
@akiyosi 
Well, after use Goneovim today in two runs (time goneovim):
Without any crash :smile: 

real	164m16.663s
user	0m29.417s
sys	0m3.458s

user	7m6.764s
sys	0m24.318s

Maybe it's time to close thos issue.

**Comment by akiyosi** [comment] 2020-07-14 13:25
@Aletz-Arce 
Thank you for your confirmation :)
Closed.

**Closed by akiyosi** 2020-07-14 13:25 UTC
